
jest.mock('../../src/config/database',()=>({query:jest.fn(),withTransaction:jest.fn()}));
const express=require('express'),request=require('supertest'),db=require('../../src/config/database');
const app=express();app.use(express.json());app.use((req,res,next)=>{req.user={id:'owner'};next()});app.use('/plans',require('../../src/routes/planningLifecycle.routes'));app.use((e,req,res,next)=>res.status(500).json({error:'Internal'}));
const id='00000000-0000-4000-8000-000000000001';
const definition={symbol:'TEST',instrument:'stock',direction:'long',currency:'USD',accountId:id,stopPrice:90,entries:[{key:'a'}],exits:[]};
beforeEach(()=>{jest.clearAllMocks();db.query.mockResolvedValue({rows:[]});db.withTransaction.mockImplementation(fn=>fn({query:db.query}));});
test('workflow reads are owner scoped and unknown plans return 404',async()=>{const r=await request(app).get('/plans/'+id+'/workflow');expect(r.status).toBe(404);expect(db.query.mock.calls[0][1]).toEqual([id,'owner'])});
test('stale management edits are rejected before any write',async()=>{db.query.mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({rows:[{id,user_id:'owner',version:2,status:'ready',definition}]});const r=await request(app).put('/plans/'+id+'/management').send({version:1,management:{entry:{a:{executed:true,units:1,price:100,time:'2026-01-01T00:00:00Z'}},exit:{}}});expect(r.status).toBe(409);expect(db.query).toHaveBeenCalledTimes(2)});
test('missing SL change reason does not touch the database',async()=>{const r=await request(app).post('/plans/'+id+'/stop').send({version:1,stopPrice:95});expect(r.status).toBe(422);expect(db.query).not.toHaveBeenCalled()});
test('unreconciled exits cannot complete a review',async()=>{db.query.mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({rows:[{id,user_id:'owner',version:1,status:'entered',definition}]}).mockResolvedValueOnce({rows:[]});const r=await request(app).post('/plans/'+id+'/review').send({version:1,notes:'Synthetic review',processFollowed:true});expect(r.status).toBe(422);expect(r.body.error).toMatch(/exited/);expect(db.query.mock.calls.some(([sql])=>sql.startsWith('UPDATE'))).toBe(false)});
test('cannot close a plan without its completed up-to-date review',async()=>{db.query.mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({rows:[{id,user_id:'owner',version:1,status:'entered',definition}]}).mockResolvedValueOnce({rows:[]});const r=await request(app).post('/plans/'+id+'/complete').send({version:1});expect(r.status).toBe(422);expect(db.query.mock.calls.some(([sql])=>sql.startsWith('UPDATE'))).toBe(false)});
test('retained charts reject non-TradingView URLs before making a request',async()=>{db.query.mockResolvedValueOnce({rows:[{id,user_id:'owner',definition:{chartUrl:'https://127.0.0.1/private'}}]});const spy=jest.spyOn(global,'fetch');const r=await request(app).post('/plans/'+id+'/chart');expect(r.status).toBe(422);expect(spy).not.toHaveBeenCalled();spy.mockRestore()});
test('private chart access scopes both plan and owner and has no public lookup',async()=>{const r=await request(app).get('/plans/'+id+'/chart');expect(r.status).toBe(404);expect(db.query.mock.calls[0][1]).toEqual([id,'owner'])});

test('legacy linked runner may be represented as an identical explicit row but cannot change its locked values',async()=>{const {normalize}=require('../../src/services/tradePlanning');const {assertEdits}=require('../../src/routes/planningLifecycle.routes');const d=normalize({title:'Synthetic',symbol:'TEST',instrument:'stock',direction:'long',currency:'USD',riskBudget:100,stopPrice:90,quantityStep:.01,entries:[{key:'a',label:'Entry',price:100,riskWeight:100}],exits:[{key:'b',label:'Target',price:110,percent:80}],runnerEstimatePrice:120});const next=normalize({...d,runnerMode:'row',exits:[...d.exits,{key:'runner',label:'Runner',price:120,percent:20}]});const client={query:jest.fn().mockResolvedValue({rows:[{action:'exit',stage_key:'runner'}]})};await expect(assertEdits(client,{id,user_id:'owner',status:'entered',definition:d},next)).resolves.toBeUndefined();next.exits[1].units=2;await expect(assertEdits(client,{id,user_id:'owner',status:'entered',definition:d},next)).rejects.toThrow(/locked/)});
