
const {sourceFills,verifyAllocation,ledger}=require('../../src/services/planningLedger');
const trade=()=>({id:'t',account_identifier:'synthetic',side:'long',symbol:'TEST',instrument_type:'stock',original_currency:'USD',commission:4,fees:0,executions:[
 {id:'a',action:'buy',quantity:10,price:100,datetime:'2026-01-01T10:00:00Z',commission:2,fees:0},
 {id:'b',action:'sell',quantity:5,price:110,datetime:'2026-01-02T10:00:00Z',commission:1,fees:0},
 {id:'c',action:'sell',quantity:5,price:120,datetime:'2026-01-03T10:00:00Z',commission:1,fees:0}
]});
const plan=()=>({definition:{symbol:'TEST',instrument:'stock',direction:'long',currency:'USD',accountId:'account',stopPrice:90,entries:[{key:'a'}],exits:[{key:'b'},{key:'c'}]},baseline:{riskBudget:100,currency:'USD'}});
const allocations=t=>sourceFills(t).map((f,i)=>({id:String(i),trade_id:t.id,source_key:f.key,stage_key:f.action==='entry'?'a':i===1?'b':'c',action:f.action,quantity:f.quantity,source_snapshot:f}));
test('FIFO result allocates source costs once through partial exits and holds original R',()=>{const t=trade(),p=plan();let r=ledger(p,allocations(t).slice(0,2),[t]);expect(r.realisedProfit).toBe(48);expect(r.openQuantity).toBe(5);expect(r.positionValue).toBe(500);expect(r.averagePrice).toBe(100);expect(r.capitalRisk).toBe(50);expect(r.economicallyClosed).toBe(false);r=ledger(p,allocations(t),[t]);expect(r.realisedProfit).toBe(146);expect(r.percentGain).toBeCloseTo(14.6);expect(r.realisedR).toBe(1.46);expect(r.economicallyClosed).toBe(true)});
test('split quantity cannot exceed remaining source fill',()=>{const t=trade(),f=sourceFills(t)[0];expect(()=>verifyAllocation(plan(),f,6,5,'entry','a',t)).toThrow(/exceeds/);expect(()=>verifyAllocation(plan(),f,5,5,'entry','a',t)).not.toThrow()});
test('source correction retains stored evidence but prevents review eligibility',()=>{const t=trade(),a=allocations(t);t.executions[0].price=101;const r=ledger(plan(),a,[t]);expect(r.unresolved).toBe(1);expect(r.realisedProfit).toBeNull();expect(r.economicallyClosed).toBe(false)});
test('source identity survives reordering and ambiguous id-less duplicates are excluded',()=>{const t=trade(),a=allocations(t);t.executions.reverse();expect(ledger(plan(),a,[t]).unresolved).toBe(0);delete t.executions[0].id;t.executions.push({...t.executions[0]});expect(sourceFills(t)).toHaveLength(2)});
test('exits cannot consume future entries or a different contract',()=>{const t=trade();t.executions[1].datetime='2025-12-31T00:00:00Z';expect(ledger(plan(),allocations(t),[t]).overExit).toBe(true)});
test('converted import monetary fields stay USD despite source currency',()=>{const t=trade();t.original_currency='GBP';t.original_entry_price_currency=80;expect(sourceFills(t)[0].currency).toBe('USD')});
test('incomplete aggregate costs block verified profit instead of ignoring costs',()=>{const t=trade();t.commission=8;const r=ledger(plan(),allocations(t),[t]);expect(r.costsUnresolved).toBe(3);expect(r.realisedProfit).toBeNull();expect(r.economicallyClosed).toBe(false)});
test('manual ticks are provisional and never qualify for completed review',()=>{const p=plan();p.management={entry:{a:{executed:true,units:2,price:100,time:'2026-01-01T00:00:00Z'}}};const r=ledger(p,[],[]);expect(r.openQuantity).toBe(2);expect(r.provisionalCount).toBe(1);expect(r.coverageComplete).toBe(false)});
test('missing currency is unknown instead of silently assumed USD',()=>{const t=trade();delete t.original_currency;expect(ledger(plan(),allocations(t),[t]).realisedProfit).toBeNull()});

test('option contracts match after PostgreSQL JSONB field ordering changes',()=>{const t=trade();t.instrument_type='option';t.contract_size=100;t.strike_price='100.000';t.expiration_date='2026-12-18';t.option_type='call';const p=plan();p.definition.instrument='option';p.definition.options={multiplier:100};const a=allocations(t);for(const x of a){const c=x.source_snapshot.contract;x.source_snapshot.contract={type:c.type,expiry:c.expiry,strike:c.strike,symbol:c.symbol}}const candidate=allocations(t)[2];expect(ledger(p,[...a.slice(0,2),candidate],[t]).overExit).toBe(false)});

test('current FX combines provisional GBP entry with linked USD entry without changing saved evidence',()=>{const t=trade(),a=allocations(t).slice(0,1),p=plan();p.definition.currency='GBP';p.definition.stopPrice=72;p.management={entry:{extra:{executed:true,units:2,price:88,time:'2026-01-02T00:00:00Z'}}};p.provisionalConversion={currency:'USD',rate:1.25};p.stopConversion=1.25;const before=JSON.stringify({a,p});const r=ledger(p,a,[t]);expect(r.currency).toBe('USD');expect(r.openQuantity).toBe(12);expect(r.positionValue).toBe(1220);expect(r.averagePrice).toBeCloseTo(1220/12);expect(r.capitalRisk).toBeCloseTo(140);expect(r.fxEstimated).toBe(true);expect(r.coverageComplete).toBe(false);expect(r.records.find(r=>r.fill.provisional).fill).toMatchObject({price:110,originalPrice:88,originalCurrency:'GBP',fxRate:1.25});expect(JSON.stringify({a,p})).toBe(before)});
test('unavailable conversion stays unresolved instead of assuming parity',()=>{const t=trade(),p=plan();p.definition.currency='GBP';p.management={entry:{extra:{executed:true,units:2,price:88,time:'2026-01-02T00:00:00Z'}}};p.provisionalConversion={currency:'USD',rate:0};const r=ledger(p,allocations(t).slice(0,1),[t]);expect(r.currency).toBeNull();expect(r.capitalRisk).toBeNull();expect(r.fxEstimated).toBe(false)});

test('row monetary values use allocated entry costs and net exit results rather than planned levels',()=>{const t=trade(),p=plan();p.definition.entries=[{key:'a',price:50}];const a=allocations(t);a[0].quantity=8;a[1].quantity=3;a[2].quantity=5;const r=ledger(p,a,[t]);expect(r.records[0].positionValue).toBe(800);expect(r.records[1].realisedProfit).toBeCloseTo(28.8);expect(r.records[2].realisedProfit).toBeCloseTo(98);expect(r.records.filter(a=>a.action==='exit').reduce((sum,a)=>sum+a.realisedProfit,0)).toBeCloseTo(r.realisedProfit);});
 test('unresolved evidence does not expose guessed exit profit',()=>{const t=trade(),a=allocations(t);t.executions[0].price=101;expect(ledger(plan(),a,[t]).records.filter(a=>a.action==='exit').every(a=>a.realisedProfit===null)).toBe(true)});

test('broker transaction rates produce account costs and profits from each entry and exit rate',()=>{const t=trade(),p=plan();p.definition.currency='GBP';p.baseline={currency:'GBP',riskBudget:100};const rates=[1.25,1.1,1.5];t.executions.forEach((e,i)=>{e.account_currency='GBP';e.broker_fx_rate=rates[i]});const a=allocations(t);let r=ledger(p,a.slice(0,2),[t]);expect(r.records[0].accountPositionValue).toBe(800);expect(r.accountPositionValue).toBe(400);expect(r.accountAveragePrice).toBe(80);expect(r.accountRealisedProfit).toBeCloseTo(550/1.1-500/1.25-1/1.25-1/1.1);r=ledger(p,a,[t]);const expected=550/1.1+600/1.5-1000/1.25-2/1.25-1/1.1-1/1.5;expect(r.accountRealisedProfit).toBeCloseTo(expected);expect(r.accountPercentGain).toBeCloseTo(expected/800*100);expect(r.accountRealisedR).toBeCloseTo(expected/100);expect(r.realisedProfit).toBe(146);expect(r.records.filter(a=>a.action==='exit').reduce((sum,a)=>sum+a.accountRealisedProfit,0)).toBeCloseTo(expected)});
test('existing source identities survive FX enrichment without rewriting stored snapshots',()=>{const t=trade(),a=allocations(t);a.forEach(a=>delete a.source_snapshot.transactionFx);const before=JSON.stringify(a),old=sourceFills(t).map(f=>({key:f.key,fingerprint:f.fingerprint}));t.executions.forEach(e=>{e.account_currency='GBP';e.broker_fx_rate=1.25});expect(sourceFills(t).map(f=>({key:f.key,fingerprint:f.fingerprint}))).toEqual(old);const r=ledger(plan(),a,[t]);expect(r.unresolved).toBe(0);expect(r.records[0].fill.transactionFx).toEqual({accountCurrency:'GBP',rate:1.25});expect(r.records[0].accountPositionValue).toBe(800);expect(JSON.stringify(a)).toBe(before)});
test('changed stored transaction rates invalidate new linked evidence and missing rates do not become current FX',()=>{const t=trade();t.executions.forEach(e=>{e.account_currency='GBP';e.broker_fx_rate=1.25});const a=allocations(t);t.executions[0].broker_fx_rate=1.3;expect(ledger(plan(),a,[t]).unresolved).toBe(1);delete t.executions[0].broker_fx_rate;const r=ledger(plan(),allocations(t),[t]);expect(r.accountFxMissing).toBe(1);expect(r.accountRealisedProfit).toBeNull();expect(r.records[0].accountPositionValue).toBeNull();expect(r.realisedProfit).toBe(146)});
test('broker rates apply the contract multiplier to option account amounts',()=>{const t=trade(),p=plan();t.instrument_type='option';t.contract_size=100;t.strike_price=100;t.expiration_date='2026-12-18';t.option_type='call';p.definition.instrument='option';p.definition.options={multiplier:100};t.executions.forEach(e=>{e.account_currency='GBP';e.broker_fx_rate=1.25});const r=ledger(p,allocations(t),[t]);expect(r.records[0].accountPositionValue).toBe(80000);expect(r.accountRealisedProfit).toBeCloseTo(14996/1.25)});

test('known entry transaction amounts remain available when another record lacks account FX',()=>{const t=trade();t.executions[0].account_currency='GBP';t.executions[0].broker_fx_rate=1.25;const r=ledger(plan(),allocations(t),[t]);expect(r.accountRealisedProfit).toBeNull();expect(r.records[0].accountCurrency).toBe('GBP');expect(r.records[0].accountPositionValue).toBe(800);expect(r.records[1].accountRealisedProfit).toBeNull()});
