const {normalize,calculate,checkReady,floorQuantity}=require('../../src/services/tradePlanning');
const draft=()=>({title:'Synthetic plan',symbol:'TEST',assetName:'Example',instrument:'stock',direction:'long',accountId:null,currency:'GBP',playbookId:null,riskBudget:100,stopPrice:90,quantityStep:.0001,entries:[{key:'a',label:'Entry A',price:100,riskWeight:25,tactic:'Condition A'},{key:'b',label:'Entry B',price:95,riskWeight:75,tactic:'Condition B'}],exits:[{key:'x',label:'Target',price:110,percent:80}],runnerRule:'Manual trailing rule',options:{}});
test('staged budgets calculate independent quantities, not equal share weights',()=>{const c=calculate(normalize(draft()));expect(c.stages.map(s=>s.quantity)).toEqual([2.5,15]);expect(c.plannedValue).toBe(1675);expect(c.runnerPercent).toBe(20);expect(c.stages.reduce((s,e)=>s+e.estimatedRisk,0)).toBe(100)});
test('reject excessive exit percentages, duplicate stages and invalid input',()=>{const d=draft();d.exits[0].percent=101;expect(()=>normalize(d)).toThrow();const e=draft();e.entries[1].key='a';expect(()=>normalize(e)).toThrow(/unique/);expect(()=>normalize()).toThrow();const n=draft();n.riskBudget=Infinity;expect(()=>normalize(n)).toThrow()});
test('invalid stop direction never produces a tradable quantity',()=>{const d=draft();d.stopPrice=105;expect(calculate(normalize(d)).stages[0].quantity).toBeNull()});
test('fractional sizing rounds down, never rounds a minimum upward',()=>{expect(floorQuantity(2.7,1)).toBe(2);expect(floorQuantity(.07,.1)).toBe(0);for(const q of [1.00000000001,.2999999999999,123456.78901234])expect(floorQuantity(q,.0001)).toBeLessThanOrEqual(q)});
test('spread stake respects configured point scale and increment',()=>{const d=draft();d.instrument='spread_bet';d.pointSize=.01;d.quantityStep=.01;d.entries=[{key:'a',label:'Entry',price:100,riskWeight:100,tactic:'Condition'}];const s=calculate(normalize(d)).stages[0];expect(s.quantity).toBe(.1);expect(s.estimatedRisk).toBe(100);expect(s.positionValue).toBeNull()});
test('options use contract share-equivalent delta once, ATR stop, whole contracts',()=>{const d=draft();d.instrument='option';d.quantityStep=1;d.riskBudget=1000;d.entries=[{key:'a',label:'Entry',price:100,riskWeight:100,tactic:'Condition'}];d.options={contractDelta:50,atr:4,atrMultiplier:.5,premium:3,multiplier:100};const s=calculate(normalize(d)).stages[0];expect(s.quantity).toBe(10);expect(s.distance).toBe(2);expect(s.stopPrice).toBe(98);expect(s.positionValue).toBe(3000);expect(s.estimatedRisk).toBe(1000)});
test('insufficient option budget yields zero contracts, not one',()=>{const d=draft();d.instrument='option';d.quantityStep=1;d.entries=d.entries.slice(0,1);d.options={contractDelta:50,atr:4,atrMultiplier:2};expect(calculate(normalize(d)).stages[0].quantity).toBe(0)});
test('Ready requires essential details and evidence but does not require a separate runner rule',()=>{const d=normalize(draft());expect(()=>checkReady(d)).toThrow(/playbook/);d.accountId='00000000-0000-4000-8000-000000000001';d.playbookId='00000000-0000-4000-8000-000000000002';d.thesis='Synthetic thesis';expect(()=>checkReady(d)).toThrow(/evidence/);d.exceptionReason='Synthetic exception';expect(checkReady(d).runnerPercent).toBe(20);d.runnerRule='';expect(checkReady(d).runnerPercent).toBe(20);d.exits.push({key:'runner',label:'Runner',price:null,percent:20,tactics:[]});d.runnerMode='row';expect(checkReady(normalize(d)).runnerPercent).toBe(20)});
test('open runner leaves whole-plan reward unavailable while fixed targets are estimated',()=>{const r=calculate(normalize(draft())).reward;expect(r.fixedTargetProfit).toBe(200);expect(r.totalPotentialProfit).toBeNull();expect(r.expectedRR).toBeNull()});
test('optional runner estimate completes profit and uses original full-plan risk',()=>{const d=draft();d.runnerEstimatePrice=120;const r=calculate(normalize(d)).reward;expect(r.totalPotentialProfit).toBe(285);expect(r.expectedRR).toBe(2.85);expect(normalize(d).runnerRule).toBe('Manual trailing rule')});
test('short reward and configured spread point scaling are applied correctly',()=>{const d=draft();d.direction='short';d.stopPrice=110;d.entries=[{key:'a',label:'Entry',price:100,riskWeight:100,tactic:'Condition'}];d.exits[0].price=90;d.runnerEstimatePrice=80;expect(calculate(normalize(d)).reward.totalPotentialProfit).toBe(120);d.instrument='spread_bet';d.pointSize=.01;d.quantityStep=.01;expect(calculate(normalize(d)).reward.totalPotentialProfit).toBe(120)});
test('missing positive-weight targets do not invent total reward and complete exits need no runner',()=>{const d=draft();d.exits[0].price=null;d.runnerEstimatePrice=120;expect(calculate(normalize(d)).reward.totalPotentialProfit).toBeNull();d.exits[0].price=110;d.exits[0].percent=100;expect(calculate(normalize(d)).reward.totalPotentialProfit).toBe(250)});
test('option reward requires explicit premium targets, not an underlying delta forecast',()=>{const d=draft();d.instrument='option';d.quantityStep=1;d.riskBudget=1000;d.entries=[{key:'a',label:'Entry',price:100,riskWeight:100,tactic:'Condition'}];d.options={contractDelta:50,atr:4,atrMultiplier:.5,premium:3,multiplier:100};let r=calculate(normalize(d)).reward;expect(r.fixedTargetProfit).toBeNull();d.exits[0].premium=4;d.exits[0].percent=100;r=calculate(normalize(d)).reward;expect(r.totalPotentialProfit).toBe(1000);expect(r.expectedRR).toBe(1)});
test('manual units are floored to the supported increment and change position risk',()=>{const d=draft();d.entries[0].units=3.55555;const s=calculate(normalize(d)).stages[0];expect(s.quantity).toBeCloseTo(3.5555,8);expect(s.estimatedRisk).toBeCloseTo(35.555,8)});

test('explicit runner preserves fixed reward while its editable target and units control total reward',()=>{const d=draft();d.runnerMode='row';d.exits.push({key:'runner',label:'Runner',price:null,percent:20});let c=calculate(normalize(d));expect(c.runnerPercent).toBe(20);expect(c.reward.fixedTargetProfit).toBe(200);expect(c.reward.totalPotentialProfit).toBeNull();d.exits[1].price=120;c=calculate(normalize(d));expect(c.reward.totalPotentialProfit).toBe(285);d.exits[1].units=1;expect(calculate(normalize(d)).reward.totalPotentialProfit).toBeCloseTo(224.285714);d.exits.pop();expect(calculate(normalize(d)).runnerPercent).toBe(0);expect(calculate(normalize(d)).reward.totalPotentialProfit).toBeNull()});
test('option runner uses its own premium target rather than an underlying-price profit estimate',()=>{const d=draft();d.runnerMode='row';d.instrument='option';d.quantityStep=1;d.riskBudget=1000;d.entries=[{key:'a',label:'Entry',price:100,riskWeight:100,tactic:'Condition'}];d.options={contractDelta:50,atr:4,atrMultiplier:.5,premium:3,multiplier:100};d.exits[0].premium=4;d.exits.push({key:'runner',label:'Runner',price:120,percent:20,premium:5});expect(calculate(normalize(d)).reward.totalPotentialProfit).toBe(1200)});
