const express=require('express');
const Joi=require('joi');
const db=require('../config/database');
const Playbook=require('../models/Playbook');
const {authenticate}=require('../middleware/auth');
const {normalize,calculate,checkFinalised,fail}=require('../services/tradePlanning');
const router=express.Router();router.use(authenticate);router.use(require("./planningLifecycle.routes"));
const uuid=Joi.string().guid({version:['uuidv4','uuidv5']});
const validateId=id=>{if(uuid.validate(id).error)fail('Invalid plan ID',400);};
const run=fn=>async(req,res,next)=>{try{await fn(req,res);}catch(e){if(e.status)return res.status(e.status).json({error:e.message});next(e);}};
async function references(client,userId,d){if(d.accountId){const a=(await client.query('SELECT id,currency,is_archived FROM user_accounts WHERE id=$1 AND user_id=$2',[d.accountId,userId])).rows[0];if(!a||a.is_archived)fail('Choose an active account you own');}if(d.playbookId&&!(await client.query('SELECT id FROM playbooks WHERE id=$1 AND user_id=$2 AND is_active=true',[d.playbookId,userId])).rows.length)fail('Choose an active playbook you own');}
async function owned(client,userId,id){const p=(await client.query('SELECT * FROM trade_plans WHERE id=$1 AND user_id=$2 FOR UPDATE',[id,userId])).rows[0];if(!p)fail('Plan not found',404);return p;}
async function event(client,p,type,snapshot){await client.query('INSERT INTO trade_plan_events(plan_id,user_id,event_type,snapshot) VALUES($1,$2,$3,$4::jsonb)',[p.id,p.user_id,type,JSON.stringify(snapshot)]);}
const map=p=>({...p,calculation:calculate(p.definition)});
router.get('/',run(async(req,res)=>{const plans=(await db.query('SELECT * FROM trade_plans WHERE user_id=$1 ORDER BY updated_at DESC LIMIT 250',[req.user.id])).rows;const commitments=(await db.query('SELECT * FROM trade_plan_commitments WHERE user_id=$1 AND status=$2 ORDER BY created_at DESC',[req.user.id,'reserved'])).rows;res.json({plans:plans.map(map),commitments,capabilities:{portfolioRisk:false,executionLinking:true,quoteInputs:false}});}));
router.post('/',run(async(req,res)=>{const d=normalize(req.body.definition);const p=await db.withTransaction(async c=>{await references(c,req.user.id,d);const p=(await c.query('INSERT INTO trade_plans(user_id,playbook_id,definition) VALUES($1,$2,$3::jsonb) RETURNING *',[req.user.id,d.playbookId,JSON.stringify(d)])).rows[0];await event(c,p,'created',d);return p;});res.status(201).json({plan:map(p)});}));
router.post('/calculate',run(async(req,res)=>res.json({calculation:calculate(normalize(req.body.definition))})));
router.get('/:id',run(async(req,res)=>{validateId(req.params.id);const p=(await db.query('SELECT * FROM trade_plans WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id])).rows[0];if(!p)fail('Plan not found',404);const history=(await db.query('SELECT event_type,created_at,snapshot FROM trade_plan_events WHERE plan_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 100',[p.id,req.user.id])).rows;res.json({plan:map(p),history});}));
router.put('/:id',run(async(req,res)=>{validateId(req.params.id);const d=normalize(req.body.definition);const p=await db.withTransaction(async c=>{const p=await owned(c,req.user.id,req.params.id);if(req.body.version!==p.version)fail('Plan changed elsewhere. Reload before saving.',409);await require('./planningLifecycle.routes').assertEdits(c,p,d);if(p.status==='cancelled')fail('Cancelled plans cannot be edited');if((await c.query("SELECT id FROM trade_plan_commitments WHERE plan_id=$1 AND status='reserved'",[p.id])).rows.length)fail('Release or reconcile the outstanding commitment before changing the plan',409);await references(c,req.user.id,d);if(p.finalised)checkFinalised(d);const next=(await c.query('UPDATE trade_plans SET definition=$1::jsonb,playbook_id=$2,version=version+1,updated_at=NOW() WHERE id=$3 RETURNING *',[JSON.stringify(d),d.playbookId,p.id])).rows[0];await event(c,p,'edited',{previous:p.definition,next:d});return next;});res.json({plan:map(p)});}));
router.post('/:id/status',run(async(req,res)=>{validateId(req.params.id);const status=req.body.status;if(!['draft','watching','cancelled'].includes(status))fail('Invalid planning status');if(status==='cancelled'&&req.body.cancellationConfirmed!==true)fail('Confirm cancellation before cancelling the plan');const p=await db.withTransaction(async c=>{const p=await owned(c,req.user.id,req.params.id);if(req.body.version!==p.version)fail('Plan changed elsewhere. Reload before changing status.',409);if(['entered','under_review','reviewed','completed'].includes(p.status))fail('Use the trade, review and close workflow for plans with executions');if(p.status==='cancelled'&&status!=='draft')fail('Reopen a cancelled plan as Draft before changing its stage');if((await c.query("SELECT id FROM trade_plan_commitments WHERE plan_id=$1 AND status='reserved'",[p.id])).rows.length)fail('Resolve and release the outstanding external-order reservation first',409);const next=(await c.query('UPDATE trade_plans SET status=$1,version=version+1,updated_at=NOW() WHERE id=$2 RETURNING *',[status,p.id])).rows[0];const pb=p.playbook_id?await Playbook.findById(p.playbook_id,req.user.id):null;await event(c,p,p.status==='cancelled'?'reopened':status,{previousStatus:p.status,status,definition:p.definition,playbookSnapshot:pb});return next;});res.json({plan:map(p)});}));
router.post('/:id/finalisation',run(async(req,res)=>{
 validateId(req.params.id);if(typeof req.body.finalised!=='boolean')fail('Choose whether the plan is finalised');
 const p=await db.withTransaction(async c=>{
  const p=await owned(c,req.user.id,req.params.id);
  if(req.body.version!==p.version)fail('Plan changed elsewhere. Reload before changing finalisation.',409);
  if(p.status!=='draft')fail('Return to Draft before changing finalisation');
  if((await c.query("SELECT id FROM trade_plan_commitments WHERE plan_id=$1 AND status='reserved'",[p.id])).rows.length)fail('Resolve the outstanding external-order reservation first',409);
  if(req.body.finalised===p.finalised)return p;
  if(req.body.finalised){await references(c,req.user.id,p.definition);checkFinalised(p.definition);}
  const next=(await c.query('UPDATE trade_plans SET finalised=$1,version=version+1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.body.finalised,p.id])).rows[0];
  const pb=p.playbook_id?await Playbook.findById(p.playbook_id,req.user.id):null;
  await event(c,p,req.body.finalised?'finalised':'finalisation_removed',{previousFinalised:p.finalised,finalised:req.body.finalised,definition:p.definition,playbookSnapshot:pb});return next;
 });res.json({plan:map(p)});
}));
router.post('/:id/commitments',run(async(req,res)=>{validateId(req.params.id);const p=await db.withTransaction(async c=>{await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`planning:${req.user.id}`]);const p=await owned(c,req.user.id,req.params.id);if(req.body.version!==p.version)fail('Plan changed elsewhere. Reload before committing.',409);if(!p.finalised||!['draft','watching'].includes(p.status))fail('Finalise the prepared plan first');await references(c,req.user.id,p.definition);checkFinalised(p.definition);const checks=req.body.checks;if(!checks||!['trigger','context','protection','data'].every(k=>checks[k]===true))fail('Confirm current trigger, context, protection and data checks');const reason=req.body.riskOverrideReason;if(typeof reason!=='string'||reason.trim().length<10||reason.length>2000)fail('Whole-portfolio risk integration is pending: record your manual verification and reason (at least 10 characters)');const stage=calculate(p.definition).stages.find(s=>s.key===req.body.stageKey);if(!stage||!(stage.quantity>0)||!(stage.estimatedRisk>0))fail('Select a valid sized entry');const existing=(await c.query("SELECT id FROM trade_plan_commitments WHERE plan_id=$1 AND stage_key=$2 AND status='reserved'",[p.id,stage.key])).rows[0];if(existing)fail('This entry already has an outstanding commitment',409);const snapshot={definition:p.definition,stage,checks,riskOverrideReason:reason.trim(),portfolioRiskVerified:false,source:'user_confirmed',version:p.version};const result=(await c.query('INSERT INTO trade_plan_commitments(plan_id,user_id,account_id,stage_key,currency,risk_amount,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb) RETURNING *',[p.id,req.user.id,p.definition.accountId,stage.key,p.definition.currency,stage.estimatedRisk,JSON.stringify(snapshot)])).rows[0];await event(c,p,'entry_committed',result);await c.query('UPDATE trade_plans SET version=version+1,updated_at=NOW() WHERE id=$1',[p.id]);return result;});res.status(201).json({commitment:p});}));
router.post('/:id/commitments/:commitmentId/release',run(async(req,res)=>{validateId(req.params.id);validateId(req.params.commitmentId);if(req.body.externalOrderNotLive!==true||typeof req.body.reason!=='string'||!req.body.reason.trim()||req.body.reason.length>2000)fail('Confirm the order was never placed or is cancelled and record the reason');await db.withTransaction(async c=>{const p=await owned(c,req.user.id,req.params.id);const result=(await c.query("UPDATE trade_plan_commitments SET status='released',released_at=NOW(),release_reason=$1 WHERE id=$2 AND plan_id=$3 AND user_id=$4 AND status='reserved' RETURNING *",[req.body.reason.trim(),req.params.commitmentId,p.id,req.user.id])).rows[0];if(!result)fail('Outstanding commitment not found',404);await event(c,p,'commitment_released',result);await c.query('UPDATE trade_plans SET version=version+1,updated_at=NOW() WHERE id=$1',[p.id]);});res.json({success:true});}));
module.exports=router;