import {mount,flushPromises} from '@vue/test-utils'
import {describe,it,expect} from 'vitest'
import PlanningSnapshot from './PlanningSnapshot.vue'
import {tradingViewSnapshot} from '@/utils/tradingViewSnapshot'
const url='https://www.tradingview.com/x/AbC123xy/'
const factory=props=>mount(PlanningSnapshot,{props:{url,asset:'Synthetic asset',...props},global:{stubs:{BaseModal:{props:['modelValue'],template:'<div v-if="modelValue" role="dialog"><slot/><slot name="footer"/></div>'}}}})
describe('TradingView snapshot preview',()=>{
 it('converts share links and accepts direct snapshot images',()=>{const s=tradingViewSnapshot(url+'?utm_source=test');expect(s.imageUrl).toBe('https://s3.tradingview.com/snapshots/a/AbC123xy.png');expect(tradingViewSnapshot(s.imageUrl)).toEqual(s)})
 it.each(['http://www.tradingview.com/x/abc/','https://tradingview.com.evil.test/x/abc/','https://evil.test/x/abc/','https://user:pass@www.tradingview.com/x/abc/','https://www.tradingview.com:8443/x/abc/','https://www.tradingview.com/chart/abc/','https://s3.tradingview.com/snapshots/z/AbC123xy.png','javascript:alert(1)'])('does not embed unsupported URLs: %s',value=>expect(tradingViewSnapshot(value)).toBeNull())
 it('does not load the image until opened and shows image/error feedback',async()=>{const w=factory();expect(w.find('img').exists()).toBe(false);await w.get('button').trigger('click');expect(w.get('img').attributes('referrerpolicy')).toBe('no-referrer');expect(w.text()).toContain('Loading snapshot');await w.get('img').trigger('load');expect(w.text()).not.toContain('Loading snapshot');await w.get('img').trigger('error');expect(w.find('img').exists()).toBe(false);expect(w.text()).toContain('could not be loaded');await w.findAll('button').find(b=>b.text()==='Retry snapshot').trigger('click');await flushPromises();expect(w.find('img').exists()).toBe(true);await w.findAll('button').find(b=>b.text()==='Close snapshot').trigger('click');expect(w.find('img').exists()).toBe(false);w.unmount()})
 it('unsupported chart links stay external and never render an iframe',()=>{const w=factory({url:'https://www.tradingview.com/chart/abc/'});expect(w.find('button').exists()).toBe(false);expect(w.find('iframe').exists()).toBe(false);expect(w.text()).toContain('Live chart layouts');w.unmount()})
 it('changing the link closes the previous snapshot',async()=>{const w=factory();await w.get('button').trigger('click');await w.setProps({url:'https://www.tradingview.com/x/Another1/'});expect(w.find('img').exists()).toBe(false);w.unmount()})
})