import {describe,it,expect} from 'vitest'
import {planMilestones,planStatusLabel} from './planningStages'
describe('plan stage journey',()=>{
 it('uses the same readable labels and highlights only the actual saved status',()=>{for(const status of ['draft','watching','entered','under_review','reviewed','completed','cancelled']){const rows=planMilestones({status});expect(rows.filter(r=>r.current).map(r=>r.key)).toEqual([status]);expect(rows.find(r=>r.current).label).toBe(planStatusLabel(status))}})
 it('retains watching, actual entry and reviewed dates and adds created/completed dates',()=>{const rows=planMilestones({status:'completed',created_at:'2026-10-01'},[{event_type:'watching',created_at:'2026-10-02'},{event_type:'trade_linked',created_at:'2026-10-05',snapshot:{action:'entry',source:{time:'2026-10-03'}}},{event_type:'reviewed',created_at:'2026-10-06'},{event_type:'completed',created_at:'2026-10-07'}]);expect(Object.fromEntries(rows.map(r=>[r.key,r.date]))).toMatchObject({draft:'1 Oct 2026',watching:'2 Oct 2026',entered:'3 Oct 2026',reviewed:'6 Oct 2026',completed:'7 Oct 2026'});expect(rows.some(r=>r.key==='ready')).toBe(false)})
 it('retains the first milestone date when a stage is revisited',()=>expect(planMilestones({status:'watching'},[{event_type:'watching',created_at:'2026-10-05'},{event_type:'watching',created_at:'2026-10-02'}]).find(r=>r.current).date).toBe('2 Oct 2026'))
 it('shows cancellation history after reopening as draft',()=>{const rows=planMilestones({status:'draft'},[{event_type:'cancelled',created_at:'2026-10-03'},{event_type:'reopened',created_at:'2026-10-04',snapshot:{status:'draft'}}]);expect(rows.find(r=>r.key==='cancelled').date).toBe('3 Oct 2026');expect(rows.find(r=>r.key==='draft').current).toBe(true)})
 it('ignores exit links for the entered date and supports user-reported entries',()=>{const rows=planMilestones({status:'entered'},[{event_type:'trade_linked',created_at:'2026-10-05',snapshot:{action:'exit',source:{time:'2026-10-05'}}},{event_type:'management_updated',created_at:'2026-10-04',snapshot:{next:{entry:{a:{executed:true,time:'2026-10-02'}}}}}]);expect(rows.find(r=>r.current).date).toBe('2 Oct 2026')})
 it('does not infer under-review dates from drafts saved before the position exited',()=>{const history=[{event_type:'review_draft_saved',created_at:'2026-10-01'},{event_type:'trade_linked',created_at:'2026-10-02',snapshot:{action:'exit'}},{event_type:'review_draft_saved',created_at:'2026-10-03'}];expect(planMilestones({status:'entered'},history).find(r=>r.key==='under_review').date).toBe('Pending');expect(planMilestones({status:'reviewed'},history,{economicallyClosed:true}).find(r=>r.key==='under_review').date).toBe('3 Oct 2026')})
 it('handles missing and invalid dates without inventing them',()=>expect(planMilestones({status:'watching'},[{event_type:'watching',created_at:'invalid'}]).find(r=>r.current).date).toBe('Pending'))
})
