
import {mount,flushPromises} from '@vue/test-utils'
import {describe,it,expect,vi,beforeEach,afterEach} from 'vitest'
import PlanningWorkspace from './PlanningWorkspace.vue'
const {get,post,put}=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn()}))
vi.mock('@/services/api',()=>({default:{get,post,put,delete:vi.fn()}}))
const definition=()=>({title:'Synthetic',symbol:'TEST',assetName:'Test asset',instrument:'stock',direction:'long',currency:'USD',accountId:null,playbookId:null,riskBudget:100,stopPrice:90,quantityStep:.01,pointSize:1,portfolioAmount:null,portfolioRiskPercent:null,setup:'',thesis:'Synthetic',chartUrl:'',runnerRule:'Trail',runnerEstimatePrice:null,preparation:[],exceptionReason:'Synthetic',entries:[{key:'a',label:'0.5',price:100,riskWeight:100,tactic:'Condition',tactics:[],marketContext:[],units:null}],exits:[{key:'b',label:'TP',price:120,percent:80,tactics:[],marketContext:[],units:null}],options:{}})
let plan,wrapper
const button=text=>wrapper.findAll('button').find(b=>b.text()===text)
const mountPage=()=>wrapper=mount(PlanningWorkspace,{props:{plan,accounts:[],playbooks:[]},global:{stubs:{RouterLink:{template:'<a><slot/></a>'},PlanningSnapshot:{template:'<section><slot/></section>'}}}})
beforeEach(()=>{vi.clearAllMocks();plan={id:'p',status:'draft',finalised:false,version:1,definition:definition(),management:{},calculation:{stages:[{price:100,quantity:10,positionValue:1000,estimatedRisk:100}],plannedQuantity:10,plannedValue:1000,reward:{fixedTargetProfit:160,fixedTargetRR:1.6}}};get.mockImplementation(url=>Promise.resolve({data:url.endsWith('/library')?{tags:[],settings:{},fx:{rates:{GBP:.8}}}:url.endsWith('/risk')?{knownRisk:300,limit:350,currency:'USD',unknown:1}:url.endsWith('/workflow')?{ledger:{records:[],openQuantity:0},history:[]}:url.endsWith('/fills')?{fills:[]}:{plan}}));put.mockImplementation((url,b)=>{if(url.endsWith('/management'))plan={...plan,version:2,management:b.management};return Promise.resolve({data:{plan}})});post.mockResolvedValue({data:{plan}})})
afterEach(()=>{wrapper?.unmount();vi.useRealTimers();vi.restoreAllMocks()})
it('uses shared full-width Entries and Exits cards without capacity controls in Plan',async()=>{mountPage();await flushPromises();expect(wrapper.text()).toContain('Entries');expect(wrapper.text()).toContain('Exits');expect(wrapper.text()).not.toContain('Chosen entry');expect(wrapper.text()).not.toContain('Portfolio risk\n');expect(wrapper.findAll('input.ladder-input').every(i=>i.classes().includes('ladder-input'))).toBe(true)})
it('management immediately projects every unlinked entry and warns before ticking',async()=>{mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();expect(wrapper.text()).toContain('With all unlinked entries US$400.00');expect(wrapper.text()).toContain('Risk limit exceeded if remaining entries are taken');expect(wrapper.text()).toContain('1 positions with unknown risk')})
it('provisional execution tick and actual tags persist via management API',async()=>{mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();const tick=wrapper.findAll('table')[0].find('input[type=checkbox]');await tick.setValue(true);await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p/management',expect.objectContaining({version:1,management:expect.objectContaining({entry:expect.objectContaining({a:expect.objectContaining({executed:true,units:10,price:100})})})}))})
it('SL cancel restores the value and never writes a stop event',async()=>{mountPage();await flushPromises();await button('Trade & Manage').trigger('click');vi.spyOn(window,'prompt').mockReturnValue(null);const stop=wrapper.findAll('input.ladder-input')[0];await stop.setValue(95);await stop.trigger('change');expect(post.mock.calls.some(([url])=>url.endsWith('/stop'))).toBe(false)})
it('requires reconciled exits before review completion and a completed review before close',async()=>{mountPage();await flushPromises();await button('Review').trigger('click');expect(button('Complete review').attributes('disabled')).toBeDefined();await button('Close').trigger('click');expect(button('Close reviewed plan').attributes('disabled')).toBeDefined()})
it('keeps option entry and exit cards shared and places rolling between them',async()=>{plan.definition.instrument='option';plan.definition.quantityStep=1;plan.definition.options={contract:'TEST',type:'call',strike:100,expiry:'2026-12-18',premium:2,multiplier:100,contractDelta:50,atr:2,atrMultiplier:2};mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();const headings=wrapper.findAll('h2').map(h=>h.text());expect(headings.indexOf('Entries')).toBeLessThan(headings.indexOf('Roll option'));expect(headings.indexOf('Roll option')).toBeLessThan(headings.indexOf('Exits'));expect(button('Add entry')).toBeTruthy()})

it('keeps risk currency conversion in display without changing the stored budget',async()=>{mountPage();await flushPromises();const risk=wrapper.find('input[aria-label="Risk amount"]');expect(Number(risk.element.value)).toBe(80);const card=wrapper.findAll('section').find(c=>c.text().includes('Risk and sizing'));await card.find('button.currency-toggle').trigger('click');expect(Number(risk.element.value)).toBe(100);await risk.setValue(120);await risk.trigger('change');await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p',expect.objectContaining({definition:expect.objectContaining({riskBudget:120,currency:'USD'})}))})
it('shows review result, assessment and timeline cards and retains completion gates',async()=>{mountPage();await flushPromises();await button('Review').trigger('click');expect(wrapper.findAll('h2').map(h=>h.text())).toEqual(expect.arrayContaining(['Original plan → actual execution','Playbook assessment','Whole-plan timeline','Review and reconciliation','Linked analysis']));expect(wrapper.findAll('textarea[placeholder="Describe deviations"]')).toHaveLength(2);await button('Close').trigger('click');expect(wrapper.text()).toContain('Completion checks');expect(wrapper.text()).toContain('Completed plans and reviews');expect(button('Close reviewed plan').attributes('disabled')).toBeDefined()})

it('automatically uses the selected playbook sole setup tag without an editable picker',async()=>{plan.definition.playbookId='book';mountPage();await wrapper.setProps({playbooks:[{id:'book',name:'Synthetic',requiredSetup:'Pullback'}]});await flushPromises();expect(wrapper.find('select[aria-label="Playbook setup"]').exists()).toBe(false);expect(wrapper.find('.tactic-chip').text()).toContain('Pullback');expect(put).not.toHaveBeenCalled();await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p',expect.objectContaining({definition:expect.objectContaining({setup:'Pullback'})}))})
it('loads selected capital without changing risk and synchronizes both risk inputs in GBP',async()=>{mountPage();await wrapper.setProps({portfolioCapital:{amount:80000,currency:'GBP',label:'Selected accounts'}});await flushPromises();expect(wrapper.find('input[aria-label="Portfolio amount"]').element.value).toBe('80000.00');expect(wrapper.find('input[aria-label="Portfolio amount"]').attributes('readonly')).toBeDefined();expect(Number(wrapper.find('input[aria-label="Portfolio risk percent"]').element.value)).toBe(.1);expect(put).not.toHaveBeenCalled();const percent=wrapper.find('input[aria-label="Portfolio risk percent"]');await percent.setValue(.3);expect(Number(wrapper.find('input[aria-label="Risk amount"]').element.value)).toBe(240);const risk=wrapper.find('input[aria-label="Risk amount"]');await risk.setValue(400);await risk.trigger('change');expect(Number(percent.element.value)).toBe(.5);await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p',expect.objectContaining({definition:expect.objectContaining({portfolioAmount:100000,riskBudget:500,portfolioRiskPercent:.5})}))})
it('runner shares editable exit quantity, percentage and tag controls and persists in management',async()=>{mountPage();await flushPromises();expect(wrapper.find('input[aria-label="exit 2 Fib level"]').element.value).toBe('Runner');await button('Trade & Manage').trigger('click');await flushPromises();await wrapper.find('input[aria-label="exit 2 price level"]').setValue(125);await wrapper.find('input[aria-label="exit 2 units"]').setValue(2);await wrapper.find('input[aria-label="Exit 2 percent"]').setValue(20);await wrapper.find('input[aria-label="exit 2 executed"]').setValue(true);await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p/management',expect.objectContaining({management:expect.objectContaining({exit:expect.objectContaining({runner:expect.objectContaining({executed:true,units:2,price:125,percent:20})})})}))})

it('provisional ticks stay editable and are never shown as broker-linked trades',async()=>{plan.management={entry:{a:{executed:true,units:2,price:100,time:'2026-01-01T00:00:00Z'}}};const original=get.getMockImplementation();get.mockImplementation((url,...args)=>url.endsWith('/workflow')?Promise.resolve({data:{ledger:{records:[{id:'provisional:entry:a',trade_id:'provisional',stage_key:'a',action:'entry',quantity:2,valid:true,fill:{provisional:true,price:100,currency:'USD'}}],provisionalCount:1,openQuantity:2},history:[]}}):original(url,...args));mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();expect(wrapper.find('input[aria-label="entry 1 units"]').attributes('disabled')).toBeUndefined();expect(wrapper.find('input[aria-label="entry 1 executed"]').attributes('disabled')).toBeUndefined();expect(wrapper.find('a[href="/trades/provisional"]').exists()).toBe(false);expect(wrapper.text()).toContain('Provisional executions · not linked');expect(wrapper.text()).not.toContain('View / add fills')});

it('unchanged management save makes no request and management cards precede entries',async()=>{mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();put.mockClear();await button('Save changes').trigger('click');await flushPromises();expect(put).not.toHaveBeenCalled();const top=wrapper.find('.management-top-grid');expect(top.text()).toContain('Final exit');expect(top.text()).toContain('Linked trades');expect(top.text()).toContain('Management timeline');expect(top.findAll('button').some(b=>b.text()==='Continue to Review')).toBe(true);expect(wrapper.find('planning-snapshot-stub').exists()).toBe(false);expect(wrapper.find('.journey').classes()).toContain('card');await wrapper.find('input[aria-label="entry 1 units"]').setValue(3);await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p/management',expect.anything())});

it('shows three recent management events and trades with independent expansion and excludes plan audit events',async()=>{const original=get.getMockImplementation();const history=['created','ready','reviewed','completed','trade_linked','stop_changed','management_updated','option_rolled'].map((event_type,i)=>({event_type,created_at:`2026-01-${String(i+1).padStart(2,'0')}T00:00:00Z`,snapshot:event_type==='management_updated'?{previous:{entry:{a:{executed:false,units:1,price:100}}},next:{entry:{a:{executed:true,units:1,price:100}}}}:{}}));const records=Array.from({length:5},(_,i)=>({id:'a'+i,trade_id:'t'+i,action:'entry',quantity:1,valid:true,fill:{price:100,currency:'USD',time:`2026-01-0${i+1}T00:00:00Z`}}));get.mockImplementation((url,...args)=>url.endsWith('/workflow')?Promise.resolve({data:{ledger:{records},history}}):original(url,...args));mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();const timeline=wrapper.find('.management-timeline');expect(timeline.findAll('strong').map(e=>e.text())).toEqual(['Option rolled for credit','Entry marked as executed · 0.5','SL invalidation level changed']);expect(timeline.text()).not.toMatch(/created|reviewed|completed/);await timeline.find('button').trigger('click');expect(timeline.findAll('strong')).toHaveLength(4);await timeline.find('button').trigger('click');expect(timeline.findAll('strong')).toHaveLength(3);const linked=wrapper.findAll('.management-top-grid section').find(e=>e.find('h2').text()==='Linked trades');expect(linked.findAll('a')).toHaveLength(3);await linked.find('button').trigger('click');expect(linked.findAll('a')).toHaveLength(5);expect(wrapper.find('.detail-grid>aside h2').text()).toBe('Position')});

it('selects ticker metadata, clears stale asset names on manual ticker changes and preserves linked-asset locks',async()=>{mountPage();await flushPromises();const picker=wrapper.findComponent({name:'SymbolAutocomplete'});picker.vm.$emit('update:modelValue','NVDA');picker.vm.$emit('select',{symbol:'NVDA',company_name:'NVIDIA'});await flushPromises();expect(wrapper.find('input[aria-label="Asset name"]').element.value).toBe('NVIDIA');picker.vm.$emit('update:modelValue','NEW.L');await flushPromises();expect(wrapper.find('input[aria-label="Asset name"]').element.value).toBe('');await wrapper.find('input[aria-label="Asset name"]').setValue('New asset');await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p',expect.objectContaining({definition:expect.objectContaining({symbol:'NEW.L',assetName:'New asset'})}));wrapper.unmount();const original=get.getMockImplementation();get.mockImplementation((url,...args)=>url.endsWith('/workflow')?Promise.resolve({data:{ledger:{records:[{fill:{provisional:false}}]},history:[]}}):original(url,...args));mountPage();await flushPromises();const locked=wrapper.findComponent({name:'SymbolAutocomplete'});expect(locked.props('disabled')).toBe(true);locked.vm.$emit('select',{symbol:'OTHER',company_name:'Other'});await flushPromises();expect(wrapper.find('input[aria-label="Asset name"]').element.value).toBe('Test asset')});

it('keeps the saved stage highlighted on every workflow screen with its recorded date',async()=>{plan={...plan,status:'watching',finalised:true,created_at:'2026-10-01'};const original=get.getMockImplementation();get.mockImplementation((url,...args)=>url.endsWith('/workflow')?Promise.resolve({data:{ledger:{records:[]},history:[{event_type:'watching',created_at:'2026-10-02'}]}}):original(url,...args));mountPage();await flushPromises();for(const screen of ['Plan','Trade & Manage','Review','Close']){await button(screen).trigger('click');await flushPromises();const current=wrapper.findAll('.journey [aria-current="step"]');expect(current).toHaveLength(1);expect(current[0].text()).toBe('2 Oct 2026Watching');expect(current[0].classes()).toContain('current');expect(wrapper.find('.journey').text()).not.toContain('Planned')} })

it('resets accidental units overrides and resumes sizing when risk changes; clearing also resets',async()=>{
 vi.useFakeTimers();const base=plan.calculation;post.mockImplementation((url,b)=>{if(url==='/trade-plans/calculate'){const q=b.definition.entries[0].units??b.definition.riskBudget/10;return Promise.resolve({data:{calculation:{...base,stages:[{...base.stages[0],quantity:q,positionValue:q*100}],plannedQuantity:q,plannedValue:q*100}}})}return Promise.resolve({data:{plan}})});
 mountPage();await flushPromises();const units=()=>wrapper.find('input[aria-label="entry 1 units"]');await units().setValue(0);await vi.advanceTimersByTimeAsync(400);expect(units().element.value).toBe('0');expect(wrapper.find('button[aria-label="Reset entry 1 units to calculated"]').exists()).toBe(true);
 await wrapper.get('button[aria-label="Reset entry 1 units to calculated"]').trigger('click');await vi.advanceTimersByTimeAsync(400);expect(units().element.value).toBe('10');expect(wrapper.find('button[aria-label="Reset entry 1 units to calculated"]').exists()).toBe(false);
 await wrapper.get('input[aria-label="Risk amount"]').setValue(160);await vi.advanceTimersByTimeAsync(400);expect(units().element.value).toBe('20');await units().setValue(0);await units().setValue('');await vi.advanceTimersByTimeAsync(400);expect(units().element.value).toBe('20');await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p',expect.objectContaining({definition:expect.objectContaining({entries:[expect.objectContaining({units:null})]})}));vi.useRealTimers()
});
it('clearing an exit override restores the calculated exit quantity',async()=>{mountPage();await flushPromises();const units=wrapper.get('input[aria-label="exit 1 units"]');await units.setValue(0);expect(units.element.value).toBe('0');expect(wrapper.find('button[aria-label="Reset exit 1 units to calculated"]').exists()).toBe(true);await units.setValue('');expect(units.element.value).toBe('8');expect(wrapper.find('button[aria-label="Reset exit 1 units to calculated"]').exists()).toBe(false)});
it('persists automatic quantities for unexecuted management rows after reset',async()=>{plan.management={entry:{a:{executed:false,units:0,price:100,time:'2026-10-09T10:00:00Z'}}};mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();await wrapper.get('button[aria-label="Reset entry 1 units to calculated"]').trigger('click');await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p/management',expect.objectContaining({management:expect.objectContaining({entry:{a:expect.objectContaining({executed:false,units:null})}})}));expect(wrapper.get('input[aria-label="entry 1 units"]').element.value).toBe('10');expect(wrapper.find('button[aria-label="Reset entry 1 units to calculated"]').exists()).toBe(false)});
it('does not allow resetting quantities from linked broker fills',async()=>{plan.definition.entries[0].units=0;const original=get.getMockImplementation();get.mockImplementation((url,...args)=>url.endsWith('/workflow')?Promise.resolve({data:{ledger:{records:[{action:'entry',stage_key:'a',quantity:10,fill:{price:100,currency:'USD',provisional:false}}]},history:[]}}):original(url,...args));mountPage();await flushPromises();expect(wrapper.get('input[aria-label="entry 1 units"]').attributes('disabled')).toBeDefined();expect(wrapper.find('button[aria-label="Reset entry 1 units to calculated"]').exists()).toBe(false)});

it('retains a published snapshot automatically after saving without a separate button',async()=>{plan.definition.chartUrl='https://www.tradingview.com/x/Synthetic123/';mountPage();await flushPromises();expect(button('Retain chart snapshot')).toBeUndefined();await button('Save changes').trigger('click');await flushPromises();expect(post).toHaveBeenCalledWith('/trade-plans/p/chart');expect(wrapper.emitted('updated')).toBeTruthy()})
it('keeps a successful plan save when retention fails and retries on the next save',async()=>{plan.definition.chartUrl='https://www.tradingview.com/x/Synthetic123/';post.mockRejectedValueOnce(new Error('Unavailable'));mountPage();await flushPromises();await button('Save changes').trigger('click');await flushPromises();expect(wrapper.text()).toContain('Plan saved, but the chart snapshot could not be retained');expect(wrapper.emitted('updated')).toBeTruthy();await button('Save changes').trigger('click');await flushPromises();expect(post.mock.calls.filter(([url])=>url==='/trade-plans/p/chart')).toHaveLength(2)})
it('does not request retention for a live chart layout',async()=>{plan.definition.chartUrl='https://www.tradingview.com/chart/Synthetic123/';mountPage();await flushPromises();await button('Save changes').trigger('click');await flushPromises();expect(post.mock.calls.some(([url])=>url.endsWith('/chart'))).toBe(false)})

it('Draft shows a persisted finalisation checkbox and no Ready action',async()=>{plan.status='draft';plan.finalised=false;post.mockImplementation((url,b)=>{if(url.endsWith('/finalisation'))plan={...plan,finalised:b.finalised,version:plan.version+1};return Promise.resolve({data:{plan}})});mountPage();await flushPromises();expect(wrapper.find('input[type=checkbox]').element.checked).toBe(false);await wrapper.find('input[type=checkbox]').setValue(true);await flushPromises();expect(post).toHaveBeenCalledWith('/trade-plans/p/finalisation',{version:1,finalised:true});expect(wrapper.text()).not.toContain('Move to Ready');expect(wrapper.find('input[type=checkbox]').element.checked).toBe(true);expect(wrapper.text()).toContain('Read-only · untick to edit')})
it('moving a finalised draft to Watching focuses Trade & Manage',async()=>{plan.status='draft';plan.finalised=true;mountPage();await flushPromises();await button('Move to Watching').trigger('click');await flushPromises();expect(post).toHaveBeenCalledWith('/trade-plans/p/status',{version:1,status:'watching'});expect(post.mock.calls.some(([url])=>url.endsWith('/finalisation'))).toBe(false);expect(wrapper.find('button[aria-current=step]').text()).toBe('Trade & Manage')})

it('finalised preparation is read-only but can be explicitly unfinalised',async()=>{plan.finalised=true;post.mockImplementation((url,b)=>{if(url.endsWith('/finalisation'))plan={...plan,finalised:b.finalised,version:2};return Promise.resolve({data:{plan}})});mountPage();await flushPromises();for(const label of ['Risk amount','entry 1 units','entry 1 price level'])expect(wrapper.find('input[aria-label="'+label+'"]').attributes('disabled')).toBeDefined();expect(button('Add entry').attributes('disabled')).toBeDefined();expect(wrapper.find('input[type=checkbox]').attributes('disabled')).toBeUndefined();await wrapper.find('input[type=checkbox]').setValue(false);await flushPromises();expect(wrapper.find('input[aria-label="Risk amount"]').attributes('disabled')).toBeUndefined();expect(post).toHaveBeenCalledWith('/trade-plans/p/finalisation',{version:1,finalised:false})})
it('unfinished Draft cannot move to Watching',async()=>{mountPage();await flushPromises();expect(button('Move to Watching').attributes('disabled')).toBeDefined();expect(post).not.toHaveBeenCalled()})
it('parent Watching transition focuses Trade & Manage while preserving the plan',async()=>{plan.finalised=true;mountPage();await flushPromises();await wrapper.setProps({plan:{...plan,status:'watching',version:2}});await flushPromises();expect(wrapper.find('button[aria-current=step]').text()).toBe('Trade & Manage');expect(wrapper.find('input[aria-label="entry 1 executed"]').exists()).toBe(true);expect(wrapper.find('input[aria-label="entry 1 units"]').attributes('disabled')).toBeUndefined()})
