
import {mount,flushPromises} from '@vue/test-utils'
import {describe,it,expect,vi,beforeEach,afterEach} from 'vitest'
import PlanningWorkspace from './PlanningWorkspace.vue'
const {get,post,put}=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn()}))
vi.mock('@/services/api',()=>({default:{get,post,put,delete:vi.fn()}}))
const definition=()=>({title:'Synthetic',symbol:'TEST',assetName:'Test asset',instrument:'stock',direction:'long',currency:'USD',accountId:null,playbookId:null,riskBudget:100,stopPrice:90,quantityStep:.01,pointSize:1,portfolioAmount:null,portfolioRiskPercent:null,setup:'',thesis:'Synthetic',chartUrl:'',runnerRule:'Trail',runnerEstimatePrice:null,preparation:[],exceptionReason:'Synthetic',entries:[{key:'a',label:'0.5',price:100,riskWeight:100,tactic:'Condition',tactics:[],marketContext:[],units:null}],exits:[{key:'b',label:'TP',price:120,percent:80,tactics:[],marketContext:[],units:null}],options:{}})
let plan,wrapper
const button=text=>wrapper.findAll('button').find(b=>b.text()===text)
const mountPage=()=>wrapper=mount(PlanningWorkspace,{props:{plan,accounts:[],playbooks:[]},global:{stubs:{RouterLink:{template:'<a><slot/></a>'},PlanningSnapshot:true}}})
beforeEach(()=>{vi.clearAllMocks();plan={id:'p',status:'ready',version:1,definition:definition(),management:{},calculation:{stages:[{price:100,quantity:10,positionValue:1000,estimatedRisk:100}],plannedQuantity:10,plannedValue:1000,reward:{fixedTargetProfit:160,fixedTargetRR:1.6}}};get.mockImplementation(url=>Promise.resolve({data:url.endsWith('/library')?{tags:[],settings:{},fx:{rates:{GBP:.8}}}:url.endsWith('/risk')?{knownRisk:300,limit:350,currency:'USD',unknown:1}:url.endsWith('/workflow')?{ledger:{records:[],openQuantity:0},history:[]}:url.endsWith('/fills')?{fills:[]}:{plan}}));put.mockImplementation((url,b)=>{if(url.endsWith('/management'))plan={...plan,version:2,management:b.management};return Promise.resolve({data:{plan}})});post.mockResolvedValue({data:{plan}})})
afterEach(()=>{wrapper?.unmount();vi.restoreAllMocks()})
it('uses shared full-width Entries and Exits cards without capacity controls in Plan',async()=>{mountPage();await flushPromises();expect(wrapper.text()).toContain('Entries');expect(wrapper.text()).toContain('Exits');expect(wrapper.text()).not.toContain('Chosen entry');expect(wrapper.text()).not.toContain('Portfolio risk\n');expect(wrapper.findAll('input.ladder-input').every(i=>i.classes().includes('ladder-input'))).toBe(true)})
it('management immediately projects every unlinked entry and warns before ticking',async()=>{mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();expect(wrapper.text()).toContain('With all unlinked entries US$400.00');expect(wrapper.text()).toContain('Risk limit exceeded if remaining entries are taken');expect(wrapper.text()).toContain('1 positions with unknown risk')})
it('provisional execution tick and actual tags persist via management API',async()=>{mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();const tick=wrapper.findAll('table')[0].find('input[type=checkbox]');await tick.setValue(true);await button('Save changes').trigger('click');await flushPromises();expect(put).toHaveBeenCalledWith('/trade-plans/p/management',expect.objectContaining({version:1,management:expect.objectContaining({entry:expect.objectContaining({a:expect.objectContaining({executed:true,units:10,price:100})})})}))})
it('SL cancel restores the value and never writes a stop event',async()=>{mountPage();await flushPromises();await button('Trade & Manage').trigger('click');vi.spyOn(window,'prompt').mockReturnValue(null);const stop=wrapper.findAll('input.ladder-input')[0];await stop.setValue(95);await stop.trigger('change');expect(post.mock.calls.some(([url])=>url.endsWith('/stop'))).toBe(false)})
it('requires reconciled exits before review completion and a completed review before close',async()=>{mountPage();await flushPromises();await button('Review').trigger('click');expect(button('Complete review').attributes('disabled')).toBeDefined();await button('Close').trigger('click');expect(button('Close reviewed plan').attributes('disabled')).toBeDefined()})
it('keeps option entry and exit cards shared and places rolling between them',async()=>{plan.definition.instrument='option';plan.definition.quantityStep=1;plan.definition.options={contract:'TEST',type:'call',strike:100,expiry:'2026-12-18',premium:2,multiplier:100,contractDelta:50,atr:2,atrMultiplier:2};mountPage();await flushPromises();await button('Trade & Manage').trigger('click');await flushPromises();const headings=wrapper.findAll('h2').map(h=>h.text());expect(headings.indexOf('Entries')).toBeLessThan(headings.indexOf('Roll option'));expect(headings.indexOf('Roll option')).toBeLessThan(headings.indexOf('Exits'));expect(button('Add entry')).toBeTruthy()})
