import {mount,flushPromises} from '@vue/test-utils'
import {describe,it,expect,vi,beforeEach} from 'vitest'
import {ref} from 'vue'
import PlanningView from './PlanningView.vue'
const {get,post,put,selectedAccount}=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn(),selectedAccount:{value:null}}))
vi.mock('@/services/api',()=>({default:{get,post,put}}))
vi.mock('@/stores/accounts',()=>({useAccountsStore:()=>({accounts:[],fetchAccounts:vi.fn().mockResolvedValue([])})}))
vi.mock('@/composables/useGlobalAccountFilter',()=>({useGlobalAccountFilter:()=>({selectedAccount,selectedAccountLabel:ref('All accounts')})}))
vi.mock('vue-router',()=>({useRouter:()=>({replace:vi.fn().mockResolvedValue()}),useRoute:()=>({params:{}})}))
const factory=()=>mount(PlanningView,{global:{stubs:{RouterLink:{template:'<a><slot/></a>'},MoneyPrivacyToggle:true}}})
beforeEach(()=>{vi.clearAllMocks();selectedAccount.value=null;get.mockImplementation(url=>Promise.resolve({data:url==='/trade-plans'?{plans:[],commitments:[]}:{playbooks:[]}}))})
describe('Planning first slice',()=>{
 it('never claims the missing portfolio capacity is verified',async()=>{const w=factory();await flushPromises();expect(w.text()).toContain('not verified');expect(w.text()).toContain('No committed entries');expect(w.text()).toContain('Ready reserves no capacity');w.unmount()})
 it('new plan offers stop-distance toggle and separate position/risk fields',async()=>{const w=factory();await flushPromises();await w.findAll('button').find(b=>b.text()==='New plan').trigger('click');expect(w.text()).toContain('Initial plan risk budget');expect(w.text()).toContain('Full planned position size');const toggle=w.findAll('button').find(b=>b.text().includes('SL distance:'));await toggle.trigger('click');expect(toggle.text()).toContain('GBP');expect(post).not.toHaveBeenCalled();w.unmount()})
})
const example=status=>({id:'example-plan',status,version:1,definition:{title:'Synthetic example',symbol:'TEST',assetName:'Test asset',instrument:'stock',direction:'long',accountId:null,currency:'GBP',playbookId:null,riskBudget:100,stopPrice:90,quantityStep:.01,thesis:'Test setup',chartUrl:'',runnerRule:'',entries:[{key:'entry1',label:'Entry 1',price:100,riskWeight:100,tactic:'Level'}],exits:[],preparation:[],options:{}},calculation:{stages:[]}})
const button=(w,text)=>w.findAll('button').find(b=>b.text()===text)
function loadExample(status){let plan=example(status);get.mockImplementation(url=>Promise.resolve({data:url==='/trade-plans'?{plans:[plan],commitments:[]}:url==='/playbooks'?{playbooks:[]}:{history:[]}}));post.mockImplementation((url,body)=>{plan={...plan,status:body.status,version:2};return Promise.resolve({data:{plan}})})}
it('All plans includes cancelled plans while active excludes them',async()=>{loadExample('cancelled');const w=factory();await flushPromises();expect(w.text()).not.toContain('Synthetic example');await w.findAll('select')[0].setValue('all');expect(w.text()).toContain('Synthetic example');
 w.unmount()})
it('cancellation requires confirmation and Keep plan performs no write',async()=>{loadExample('draft');const w=factory();await flushPromises();await button(w,'Open plan').trigger('click');await flushPromises();await button(w,'Cancel plan').trigger('click');expect(post).not.toHaveBeenCalled();await button(w,'Keep plan').trigger('click');expect(post).not.toHaveBeenCalled();expect(w.find('[aria-label="Confirm plan cancellation"]').exists()).toBe(false);await button(w,'Cancel plan').trigger('click');await button(w,'Confirm cancellation').trigger('click');await flushPromises();expect(post).toHaveBeenCalledWith('/trade-plans/example-plan/status',{status:'cancelled',version:1,cancellationConfirmed:true});expect(button(w,'Reopen as Draft')).toBeTruthy();w.unmount()})
it('reopens a cancelled plan without trying to edit the read-only definition',async()=>{loadExample('cancelled');const w=factory();await flushPromises();await w.findAll('select')[0].setValue('cancelled');await button(w,'Open plan').trigger('click');await flushPromises();await button(w,'Reopen as Draft').trigger('click');await flushPromises();expect(put).not.toHaveBeenCalled();expect(post).toHaveBeenCalledWith('/trade-plans/example-plan/status',{status:'draft',version:1,cancellationConfirmed:false});expect(button(w,'Cancel plan')).toBeTruthy();w.unmount()})
it('shows unmet entry checks beside confirmation without submitting a commitment',async()=>{loadExample('ready');const w=factory();await flushPromises();await button(w,'Prepare entry').trigger('click');await flushPromises();await button(w,'Confirm chosen entry commitment').trigger('click');expect(w.get('#entry-confirmation-feedback').text()).toContain('Complete all four entry checks');expect(post).not.toHaveBeenCalled();w.unmount()})
it('shows the missing manual verification reason and API errors at the confirmation button',async()=>{loadExample('ready');const w=factory();await flushPromises();await button(w,'Prepare entry').trigger('click');await flushPromises();for(const c of w.findAll('input[type=checkbox]'))await c.setValue(true);await button(w,'Confirm chosen entry commitment').trigger('click');expect(w.get('#entry-confirmation-feedback').text()).toContain('at least 10 characters');expect(post).not.toHaveBeenCalled();await w.get('textarea[placeholder="Record how you checked all-account risk, protection, capacity and source freshness"]').setValue('Synthetic manual checks verified');post.mockRejectedValueOnce({response:{data:{error:'Plan changed elsewhere. Reload before committing.'}}});await button(w,'Confirm chosen entry commitment').trigger('click');await flushPromises();expect(w.get('#entry-confirmation-feedback').text()).toContain('Reload before committing');w.unmount()})