<template>
  <div class="content-wrapper py-8 space-y-6">
    <nav class="flex gap-7 border-b border-gray-700" aria-label="Dashboard tabs"><RouterLink to="/dashboard" class="pb-3 text-gray-400">Trading</RouterLink><RouterLink to="/dashboard/portfolio" class="pb-3 text-gray-400">Portfolio</RouterLink><RouterLink to="/dashboard/planning" class="pb-3 border-b-2 border-primary-500 text-primary-400" @click="selected=null">Planning</RouterLink></nav>
    <div class="flex flex-wrap justify-between gap-4"><div><h1 class="heading-page">{{ selected ? assetLabel : 'Planning' }}</h1><p class="text-gray-400 mt-1">{{ selected ? 'Prepare your setup before choosing an entry.' : 'Prepared plans wait for their trigger. Ready reserves no capacity.' }}</p></div><div class="flex gap-2 items-center"><MoneyPrivacyToggle/><button class="btn-primary" @click="newPlan">New plan</button><button v-if="selected" class="btn-secondary" @click="closeDetail">All plans</button></div></div>
    <div class="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-sm"><strong>First working slice on test.</strong> Planning, sizing and explicit entry reservations are available. Whole-portfolio risk, broker constraints, FX, execution linking and review are still being connected. Capacity is not verified by this page; entry commitment requires a recorded manual check.</div>
    <p v-if="error" class="rounded-md bg-red-500/10 p-4 text-red-400" role="alert">{{ error }}</p>
    <div class="card p-5"><div class="flex justify-between flex-wrap gap-4"><h2 class="font-semibold">Outstanding entry commitments · all accounts</h2><span class="text-sm text-gray-400">Display filters do not change this scope</span></div><p v-if="!commitments.length" class="text-gray-400 mt-3">No committed entries.</p><div v-for="[currency,total] in commitmentTotals" :key="currency" class="mt-2">{{ money(total,currency) }} reserved in {{ currency }}</div><p class="text-sm text-amber-400 mt-3">Open-position risk and available capacity: not yet integrated. These totals are reservations only.</p></div>
    <template v-if="!selected">
      <div class="flex flex-wrap gap-3"><label>Stage<select v-model="stageFilter" class="input"><option value="active">All active</option><option value="all">All plans</option><option value="ready">Ready</option><option value="watching">Watching</option><option value="draft">Draft</option><option value="cancelled">Cancelled</option></select></label><label>Drafts<select v-model="draftFilter" class="input"><option value="all">Account filter from navigation</option><option value="unassigned">Unassigned plans</option></select></label><div class="text-sm text-gray-400 self-end pb-2">All active dates · {{ selectedAccountLabel }}</div></div>
      <div class="card p-5 overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Asset / playbook</th><th>Stage</th><th>Account</th><th>Planned risk budget</th><th>Next action</th></tr></thead><tbody><tr v-for="p in visiblePlans" :key="p.id"><td><button class="text-primary-400 font-semibold text-left" @click="openPlan(p)">{{ label(p.definition) }}</button><div>{{ p.definition.title }}</div><div class="text-gray-400">{{ playbookName(p.definition.playbookId) }}</div></td><td>{{ statusLabel(p.status) }}</td><td>{{ accountName(p.definition.accountId) }}</td><td>{{ money(p.definition.riskBudget,p.definition.currency) }}</td><td><button class="btn-secondary" @click="openPlan(p)">{{ p.status==='ready'?'Prepare entry':'Open plan' }}</button></td></tr></tbody></table><p v-if="!visiblePlans.length" class="text-gray-400 mt-4">No plans match the selection.</p><p v-if="loading" class="mt-4">Loading plans…</p></div>
    </template>
    <template v-else-if="!hideAmounts">
      <div class="flex flex-wrap items-center gap-3"><span class="rounded bg-primary-500/10 text-primary-400 px-3 py-1">{{ statusLabel(selected.status) }}</span><span class="text-sm text-gray-400">{{ saveState }}</span><button class="btn-secondary" :disabled="saving||locked||selected.status==='cancelled'" @click="save">Save plan</button><button v-if="selected.id&&selected.status!=='ready'&&selected.status!=='cancelled'" class="btn-primary" :disabled="saving" @click="setStatus('ready')">Mark Ready</button><button v-if="selected.id&&selected.status==='ready'&&!locked" class="btn-secondary" @click="setStatus('watching')">Return to Watching</button><button v-if="selected.id&&selected.status!=='cancelled'&&!locked" class="btn-secondary" @click="cancelPending=true">Cancel plan</button><button v-if="selected.id&&selected.status==='cancelled'&&!locked" class="btn-secondary" :disabled="saving" @click="setStatus('draft')">Reopen as Draft</button></div>
      <section v-if="cancelPending" class="rounded-md border border-amber-500/40 bg-amber-500/10 p-4" aria-label="Confirm plan cancellation"><p>Cancel this plan? It will leave All active, but its details and history will stay saved. You can find it under Cancelled and reopen it as a Draft.</p><div class="flex gap-3 mt-3"><button class="btn-secondary" :disabled="saving" @click="cancelPending=false">Keep plan</button><button class="btn-secondary text-red-400" :disabled="saving" @click="setStatus('cancelled')">Confirm cancellation</button></div></section>
      <p v-if="selected.status==='cancelled'" class="text-gray-400">This plan is retained with its history. Reopen as Draft to review and edit it; this does not mark it Ready or reserve capacity.</p>
      <p v-if="locked" class="text-amber-400">An entry is committed. Resolve its external order before editing this plan.</p>
      <fieldset :disabled="locked||selected.status==='cancelled'" class="space-y-5">
        <div class="grid lg:grid-cols-2 gap-5"><section class="card p-5"><h2 class="font-semibold text-lg mb-4">Asset and setup</h2><div class="grid sm:grid-cols-2 gap-4"><label>Ticker<input v-model="form.symbol" class="input" maxlength="40" placeholder="NVDA"></label><label>Asset name<input v-model="form.assetName" class="input" placeholder="NVIDIA"></label><label>Plan title<input v-model="form.title" class="input" maxlength="160"></label><label>Instrument<select v-model="form.instrument" class="input"><option value="stock">Stock / ETF shares</option><option value="crypto">Crypto</option><option value="spread_bet">Spread betting</option><option value="option">Single-leg option</option></select></label><label>Underlying direction<select v-model="form.direction" class="input"><option value="long">Long / bullish</option><option value="short">Short / bearish</option></select></label><label>Account<select v-model="form.accountId" class="input" @change="chooseAccount"><option :value="null">Unassigned</option><option v-for="a in accounts" :key="a.id" :value="a.id">{{ a.accountName }} · {{ a.currency }}</option></select></label><label>Playbook<select v-model="form.playbookId" class="input" @change="useTemplate"><option :value="null">Choose playbook</option><option v-for="p in playbooks" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>Account / price currency<input v-model="form.currency" class="input" maxlength="3"></label></div><div v-if="pendingTemplate" class="rounded-md border border-primary-500/30 p-3 mt-4"><p>Apply this playbook template? This replaces the entry and exit ladder.</p><button type="button" class="btn-primary mt-2" @click="applyTemplate">Apply planning template</button><button type="button" class="btn-secondary ml-2" @click="pendingTemplate=null">Keep current ladder</button></div><label class="block mt-4">Thesis<textarea v-model="form.thesis" class="input" rows="3"></textarea></label><label class="block mt-4">TradingView snapshot link<input v-model="form.chartUrl" type="url" class="input" placeholder="https://…"></label><p class="text-sm text-gray-400 mt-2">Use a TradingView snapshot link to view the chart in the Chart evidence section below.</p></section>
        <section class="card p-5"><h2 class="font-semibold text-lg mb-4">Risk and sizing · {{ form.currency }}</h2><div class="grid sm:grid-cols-2 gap-4"><label>Initial plan risk budget<input v-model.number="form.riskBudget" type="number" min="0" step="any" class="input"></label><label v-if="form.instrument!=='option'">Stop-loss price<input v-model.number="form.stopPrice" type="number" min="0" step="any" class="input"></label><label>Quantity / stake increment<input v-model.number="form.quantityStep" type="number" min="0" step="any" class="input"><small>Round down to this broker-supported increment.</small></label><label v-if="form.instrument==='spread_bet'">Price units per stake point<input v-model.number="form.pointSize" type="number" min="0" step="any" class="input"></label></div>
        <div v-if="form.instrument==='option'" class="grid sm:grid-cols-2 gap-4 mt-4"><label>Contract identity<input v-model="form.options.contract" class="input"></label><label>Type<select v-model="form.options.type" class="input"><option>call</option><option>put</option></select></label><label>Strike<input v-model.number="form.options.strike" type="number" step="any" class="input"></label><label>Expiry<input v-model="form.options.expiry" type="date" class="input"></label><label>Premium per underlying unit<input v-model.number="form.options.premium" type="number" step="any" class="input"></label><label>Contract multiplier<input v-model.number="form.options.multiplier" type="number" step="any" class="input"></label><label>Share-equivalent delta / contract<input v-model.number="form.options.contractDelta" type="number" step="any" class="input" placeholder="50"></label><label>Completed-candle ATR<input v-model.number="form.options.atr" type="number" step="any" class="input"></label><label>ATR multiplier<input v-model.number="form.options.atrMultiplier" type="number" step="any" class="input"></label><label>ATR lookback<input v-model.number="form.options.atrPeriod" type="number" class="input"></label><label>ATR timeframe<input v-model="form.options.atrTimeframe" class="input"></label><label>ATR / delta source<input v-model="form.options.source" class="input"></label><label>Evidence date<input v-model="form.options.asOf" type="date" class="input"></label></div>
        <p class="text-sm text-amber-400 mt-4">Sizing inputs are manually supplied in this slice. Allow for fees/slippage when choosing the risk budget; costs are not configured. Cross-currency sizing is unavailable.</p><div class="mt-4 grid grid-cols-2 gap-4"><div><small>Full planned position size</small><p class="text-xl font-semibold">{{ money(calculation?.plannedValue,form.currency) }}</p></div><div><small>Actual filled position</small><p class="text-gray-400">Execution linking pending</p></div></div></section></div>
        <section class="card p-5"><div class="flex justify-between gap-3"><h2 class="font-semibold text-lg">Entry ladder · planned</h2><div class="flex gap-2"><button class="btn-secondary" type="button" @click="percentStop=!percentStop">SL distance: {{ percentStop?'%':form.currency }}</button><button class="btn-secondary" type="button" @click="addEntry">Add entry</button></div></div><div class="overflow-auto"><table class="w-full text-sm"><thead><tr><th>Planned entry</th><th>Entry / underlying price</th><th>Risk %</th><th>Cash risk</th><th>Quantity</th><th>Position size</th><th>SL distance</th><th></th></tr></thead><tbody><tr v-for="(e,i) in form.entries" :key="e.key"><td><input v-model="e.label" class="input min-w-32" aria-label="Entry label"></td><td><input v-model.number="e.price" type="number" step="any" class="input min-w-28" aria-label="Entry price"></td><td><input v-model.number="e.riskWeight" type="number" step="any" class="input w-24" aria-label="Risk weight"></td><td>{{ money(stage(i)?.cashRisk,form.currency) }}</td><td>{{ number(stage(i)?.quantity) }} {{ form.instrument==='spread_bet'?'per point':form.instrument==='option'?'contracts':'units' }}</td><td>{{ money(stage(i)?.positionValue,form.currency) }}</td><td>{{ percentStop?number(stage(i)?.slPercent)+'%':money(stage(i)?.distance,form.currency) }}</td><td><button class="text-red-400" type="button" :disabled="form.entries.length===1" @click="form.entries.splice(i,1)">Remove</button></td></tr><tr v-for="e in form.entries" :key="'tactic-'+e.key"><td colspan="8"><label>{{ e.label }} · trigger / tactic<input v-model="e.tactic" class="input" placeholder="Price-zone or indicator conditions; include timeframe"></label></td></tr></tbody></table></div><button class="btn-secondary mt-3" type="button" @click="calculatePreview">Update sizing preview</button><p class="text-gray-400 text-sm mt-2">Unfilled entries reserve nothing. Preview amounts reflect the last successful calculation.</p></section>
        <div class="grid lg:grid-cols-2 gap-5"><section class="card p-5"><div class="flex justify-between"><h2 class="font-semibold text-lg">Exit ladder</h2><button class="btn-secondary" type="button" @click="addExit">Add target</button></div><div v-for="(e,i) in form.exits" :key="e.key" class="grid grid-cols-4 gap-2 mt-3"><input v-model="e.label" class="input" aria-label="Target label"><input v-model.number="e.price" type="number" step="any" class="input" aria-label="Target price"><input v-model.number="e.percent" type="number" step="any" class="input" aria-label="Exit percentage"><button type="button" class="text-red-400" @click="form.exits.splice(i,1)">Remove</button></div><p class="mt-3">Runner: {{ runner }}%</p><label class="block mt-3">Runner / exit-management rule<textarea v-model="form.runnerRule" class="input" rows="2"></textarea></label><small>Exit percentages use actual filled quantity once executions are connected.</small></section><section class="card p-5"><h2 class="font-semibold text-lg">Stable preparation</h2><label v-for="p in form.preparation" :key="p.key" class="flex gap-3 items-start my-3"><input v-model="p.done" type="checkbox" class="mt-1">{{ p.label }}</label><label>Evidence exception reason<textarea v-model="form.exceptionReason" class="input" rows="2" placeholder="Explain incomplete chart or preparation evidence"></textarea></label><p class="text-gray-400 text-sm mt-3">Today's context and capacity are checked at Prepare entry, not when marking Ready.</p></section></div>
      </fieldset>
      <PlanningSnapshot :url="form.chartUrl" :asset="assetLabel"/>
      <section v-if="selected.id&&selected.status==='ready'" class="card p-5 space-y-4"><h2 class="font-semibold text-lg">Prepare entry · {{ assetLabel }}</h2><label class="block">Planned entry<select v-model="chosenStage" class="input"><option v-for="e in form.entries" :key="e.key" :value="e.key">{{ e.label }}</option></select></label><div class="grid sm:grid-cols-3 gap-4"><div><small>Position size</small><p class="text-xl">{{ money(chosen?.positionValue,form.currency) }}</p></div><div><small>Quantity</small><p class="text-xl">{{ number(chosen?.quantity) }}</p></div><div><small>Stage cash risk</small><p class="text-xl">{{ money(chosen?.estimatedRisk,form.currency) }}</p></div></div><p>Stop-loss price: {{ money(chosen?.stopPrice,form.currency) }} · SL distance: {{ percentStop?number(chosen?.slPercent)+'%':money(chosen?.distance,form.currency) }}</p><label v-for="(name,key) in checkLabels" :key="key" class="flex gap-3"><input v-model="checks[key]" type="checkbox">{{ name }}</label><label class="block">Manual portfolio/capacity verification reason<textarea v-model="riskReason" class="input" rows="2" placeholder="Record how you checked all-account risk, protection, capacity and source freshness"></textarea></label><p class="text-amber-400 text-sm">Open risk, limits, available capacity and cost allowances are not verified automatically. Proceeding records your explicit manual verification; it does not place an order.</p><button class="btn-primary" :disabled="saving||locked" @click="commit">Confirm chosen entry commitment</button></section>
      <section v-if="planCommitments.length" class="card p-5"><h2 class="font-semibold text-lg">Awaiting execution confirmation</h2><div v-for="c in planCommitments" :key="c.id" class="mt-4"><p>{{ c.snapshot.stage.label }} · {{ money(c.risk_amount,c.currency) }} reserved · {{ new Date(c.created_at).toLocaleString() }}</p><label class="block mt-3">Release reason<input v-model="releaseReason" class="input"></label><label class="flex gap-3 mt-3"><input v-model="releaseConfirmed" type="checkbox">I confirm the unfilled order was never placed or is cancelled.</label><button class="btn-secondary mt-2" :disabled="!releaseConfirmed||!releaseReason.trim()" @click="release(c)">Confirm release of unfilled reservation</button><p class="text-sm text-gray-400">Do not release a filled order. Execution reconciliation is the next slice.</p></div></section>
      <details v-if="history.length" class="card p-5"><summary class="cursor-pointer">Plan history</summary><div v-for="(e,i) in history" :key="i" class="py-2 border-b border-gray-700">{{ e.event_type.replaceAll('_',' ') }} · {{ new Date(e.created_at).toLocaleString() }}</div></details>
    </template>
    <p v-else class="card p-5">Plan details are concealed while monetary privacy is enabled. Use the eye control to reveal and edit them.</p>
  </div>
</template>
<script setup>
import {ref,computed,onMounted,watch,onBeforeUnmount} from 'vue'
import {useRouter,useRoute} from 'vue-router'
import api from '@/services/api'
import {useAccountsStore} from '@/stores/accounts'
import {useGlobalAccountFilter} from '@/composables/useGlobalAccountFilter'
import {accountSelection} from '@/utils/accountSelection'
import {useDashboardPrivacy,MONEY_MASK} from '@/composables/useDashboardPrivacy'
import MoneyPrivacyToggle from '@/components/dashboard/MoneyPrivacyToggle.vue'
import PlanningSnapshot from '@/components/planning/PlanningSnapshot.vue'
const {hideAmounts}=useDashboardPrivacy(),router=useRouter(),route=useRoute(),accountStore=useAccountsStore()
const {selectedAccount,selectedAccountLabel}=useGlobalAccountFilter()
const cancelPending=ref(false),releaseReason=ref(''),releaseConfirmed=ref(false),pendingTemplate=ref(null),plans=ref([]),commitments=ref([]),playbooks=ref([]),selected=ref(null),form=ref(null),calculation=ref(null),history=ref([]),error=ref(''),loading=ref(false),saving=ref(false),saveState=ref(''),dirty=ref(false),stageFilter=ref('active'),draftFilter=ref('all'),percentStop=ref(true),chosenStage=ref('stage1'),riskReason=ref(''),checks=ref({trigger:false,context:false,protection:false,data:false})
const checkLabels={trigger:'Trigger and chart conditions confirmed',context:"Today's journal context and position review completed",protection:'Existing position protection checked',data:'Balance, quote, stop and broker quantity constraints checked'}
const accounts=computed(()=>accountStore.accounts.filter(a=>!a.isArchived))
let timer=null,hydrating=false,previewSequence=0
const label=d=>d.assetName?`${d.assetName} (${d.symbol})`:d.symbol
const assetLabel=computed(()=>form.value?label(form.value):'Planning')
const accountName=id=>accounts.value.find(a=>a.id===id)?.accountName||'Unassigned'
const playbookName=id=>playbooks.value.find(p=>p.id===id)?.name||'No playbook'
const statusLabel=s=>({draft:'Draft',watching:'Watching',ready:'Ready',cancelled:'Cancelled'}[s]||s)
function money(v,c){if(hideAmounts.value)return MONEY_MASK;if(v==null||v==='')return 'Unavailable';try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(Number(v))}catch{return `${number(v)} ${c}`}}
function number(v){return v==null?'Unavailable':Number(v).toLocaleString(undefined,{maximumFractionDigits:6})}
const stage=i=>calculation.value?.stages[i]
const chosen=computed(()=>calculation.value?.stages.find(e=>e.key===chosenStage.value))
const runner=computed(()=>Math.max(0,100-(form.value?.exits||[]).reduce((s,e)=>s+(Number(e.percent)||0),0)))
const planCommitments=computed(()=>commitments.value.filter(c=>c.plan_id===selected.value?.id))
const locked=computed(()=>planCommitments.value.length>0)
const commitmentTotals=computed(()=>Object.entries(commitments.value.reduce((s,c)=>{s[c.currency]=(s[c.currency]||0)+Number(c.risk_amount);return s},{})))

const visiblePlans=computed(()=>{const selection=accountSelection(selectedAccount.value);return plans.value.filter(p=>{const a=accounts.value.find(a=>a.id===p.definition.accountId);const identifier=a?.accountIdentifier||a?.accountName;const matches=selection===null||selection.includes(identifier);return matches&&(draftFilter.value!=='unassigned'||!p.definition.accountId)&&(stageFilter.value==='all'||(stageFilter.value==='active'?p.status!=='cancelled':p.status===stageFilter.value))})})
function defaults(){return {title:'New trade plan',symbol:'',assetName:'',instrument:'stock',direction:'long',accountId:null,currency:'GBP',playbookId:null,riskBudget:null,stopPrice:null,quantityStep:0.0001,pointSize:1,thesis:'',chartUrl:'',runnerRule:'',exceptionReason:'',preparation:[{key:'setup',label:'Setup conditions and chart evidence reviewed',done:false},{key:'risk',label:'Stop, risk and sizing prepared',done:false},{key:'exit',label:'Exit-management rules prepared',done:false}],entries:[{key:'stage1',label:'Entry 1',price:null,riskWeight:100,tactic:''}],exits:[],options:{contract:'',type:'call',strike:null,expiry:null,premium:null,multiplier:100,contractDelta:null,atr:null,atrMultiplier:2,atrPeriod:14,atrTimeframe:'Daily',source:'',asOf:null}}}
function payload(){const d=JSON.parse(JSON.stringify(form.value));for(const k of ['riskBudget','stopPrice'])if(d[k]==='')d[k]=null;d.symbol=d.symbol.trim().toUpperCase();for(const e of [...d.entries,...d.exits])if(e.price==='')e.price=null;for(const k of ['strike','premium','contractDelta','atr','expiry','asOf'])if(d.options[k]==='')d.options[k]=null;return d}
function failure(e){error.value=e.response?.data?.error||'Request failed. Your unsaved edits remain here.'}
async function load(){loading.value=true;try{const r=await api.get('/trade-plans');plans.value=r.data.plans;commitments.value=r.data.commitments}finally{loading.value=false}}
function adopt(p){cancelPending.value=false;hydrating=true;selected.value=p;form.value=JSON.parse(JSON.stringify(p.definition));calculation.value=p.calculation;chosenStage.value=form.value.entries[0].key;dirty.value=false;saveState.value='Saved';queueMicrotask(()=>hydrating=false)}
async function openPlan(p){if(dirty.value&&!confirm('Leave unsaved edits?'))return;clearTimeout(timer);error.value='';adopt(p);await router.replace(`/dashboard/planning/${p.id}`);try{history.value=(await api.get(`/trade-plans/${p.id}`)).data.history}catch(e){failure(e)}}
function newPlan(){cancelPending.value=false;if(dirty.value&&!confirm('Leave unsaved edits?'))return;clearTimeout(timer);hydrating=true;selected.value={id:null,status:'draft',version:0};form.value=defaults();calculation.value=null;history.value=[];saveState.value='New draft · save to enable autosave';dirty.value=false;error.value='';router.replace('/dashboard/planning');queueMicrotask(()=>hydrating=false)}
function closeDetail(){if(dirty.value&&!confirm('Leave unsaved edits?'))return;clearTimeout(timer);selected.value=null;form.value=null;router.replace('/dashboard/planning')}
function chooseAccount(){const a=accounts.value.find(a=>a.id===form.value.accountId);if(a)form.value.currency=a.currency}
function useTemplate(){const p=playbooks.value.find(p=>p.id===form.value.playbookId);const t=p?.planningTemplate;if(!t)return;pendingTemplate.value=t}
function applyTemplate(){const t=pendingTemplate.value;if(!t)return;pendingTemplate.value=null;form.value.entries=t.entries.map(e=>({...e,price:null,tactic:e.tactic||''}));form.value.exits=t.exits.map(e=>({...e,price:null}));form.value.runnerRule=t.runnerRule||''}
function addEntry(){form.value.entries.push({key:crypto.randomUUID().replaceAll('-',''),label:`Entry ${form.value.entries.length+1}`,price:null,riskWeight:0,tactic:''})}
function addExit(){form.value.exits.push({key:crypto.randomUUID().replaceAll('-',''),label:`TP${form.value.exits.length+1}`,price:null,percent:0})}
async function calculatePreview(){const seq=++previewSequence;try{const r=await api.post('/trade-plans/calculate',{definition:payload()});if(seq===previewSequence)calculation.value=r.data.calculation}catch(e){failure(e)}}
async function save(){if(saving.value)return false;saving.value=true;error.value='';saveState.value='Saving…';const d=payload();try{const r=selected.value.id?await api.put(`/trade-plans/${selected.value.id}`,{definition:d,version:selected.value.version}):await api.post('/trade-plans',{definition:d});selected.value=r.data.plan;calculation.value=r.data.plan.calculation;dirty.value=JSON.stringify(payload())!==JSON.stringify(d);saveState.value=dirty.value?'Edits pending':'Saved';await load();if(dirty.value){clearTimeout(timer);timer=setTimeout(save,900)}return true}catch(e){failure(e);saveState.value='Save failed · edits retained';return false}finally{saving.value=false}}
async function setStatus(status){if(status==='cancelled'&&!cancelPending.value)return;if(dirty.value&&!(await save()))return;try{const r=await api.post(`/trade-plans/${selected.value.id}/status`,{status,version:selected.value.version,cancellationConfirmed:status==='cancelled'&&cancelPending.value});adopt(r.data.plan);await load()}catch(e){failure(e)}}
async function commit(){if(dirty.value&&!(await save()))return;try{await api.post(`/trade-plans/${selected.value.id}/commitments`,{stageKey:chosenStage.value,version:selected.value.version,checks:checks.value,riskOverrideReason:riskReason.value});await load();adopt(plans.value.find(p=>p.id===selected.value.id));saveState.value='Committed · awaiting execution confirmation'}catch(e){failure(e)}}
async function release(c){if(!releaseConfirmed.value||!releaseReason.value.trim())return;const reason=releaseReason.value.trim();try{await api.post(`/trade-plans/${selected.value.id}/commitments/${c.id}/release`,{externalOrderNotLive:true,reason});await load();adopt(plans.value.find(p=>p.id===selected.value.id))}catch(e){failure(e)}}
watch(form,()=>{if(hydrating||!selected.value||locked.value)return;dirty.value=true;saveState.value=selected.value.id?'Edits pending':'New draft · save to enable autosave';clearTimeout(timer);if(selected.value.id)timer=setTimeout(save,900)},{deep:true})
watch(()=>form.value?.instrument,v=>{if(v==='option'&&!hydrating)form.value.quantityStep=1})
function leaving(e){if(dirty.value){e.preventDefault();e.returnValue=''}}
onMounted(async()=>{window.addEventListener('beforeunload',leaving);try{await Promise.all([load(),accountStore.fetchAccounts(),api.get('/playbooks').then(r=>playbooks.value=r.data.playbooks)]);if(route.params.id){const p=plans.value.find(p=>p.id===route.params.id);if(p)await openPlan(p);else error.value='Plan not found'}}catch(e){failure(e)}})
onBeforeUnmount(()=>{clearTimeout(timer);window.removeEventListener('beforeunload',leaving)})
</script>
<style scoped>th{text-align:left;color:#9ca3af;font-weight:500;white-space:nowrap}td,th{padding:12px 10px;border-bottom:1px solid #374151}td:first-child,th:first-child{padding-left:0}small{color:#9ca3af}input[type=checkbox]{accent-color:#f97316;width:18px;min-width:18px;height:18px}fieldset:disabled{opacity:.65}</style>